#cloud-config

users:
  - name: mlgirl
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
    home: /home/mlgirl
    create_home: true

package_update: true
package_upgrade: true

packages:
  - git
  - python3-pip
  - libgl1-mesa-glx
  - ffmpeg

write_files:
  - path: /home/mlgirl/requirements.txt
    owner: mlgirl:mlgirl
    permissions: '0644'
    content: |
      torch
      torchvision
      torchaudio
      transformers>=4.15.0
      datasets
      evaluate
      huggingface_hub
      timm
      tensorboard
      matplotlib
      scikit-learn
      seaborn
      Pillow
      opencv-python
      numpy
      pandas
      tqdm
      accelerate
      pyyaml
      click

runcmd:
  - echo "Installing python packages..."
  - pip3 install --upgrade pip
  - pip3 install -r /home/mlgirl/requirements.txt
  - echo "Cloning repo..."
  - git clone https://github.com/NailaRais/image-classifier.git /home/mlgirl/image-classifier
  - cd /home/mlgirl/image-classifier
  - echo "Starting training..."
  - python3 train.py
